import type { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design Homepage Wireframe',
    description: 'Discuss layout with the marketing team for alignment on visual hierarchy and content placement.',
    priority: 'low',
    dueDate: '2025-11-02',
    assignees: ['Davis Donin', 'Talan Korsgaard'],
    status: 'todo',
    taskType: 'review',
    tags: ['ux', 'wireframe', 'homepage'],
    createdAt: '2025-09-20T10:35:00.000Z',
    comments: 12,
    links: 1,
    subTasksCompleted: 0,
    subTasksTotal: 3,
  },
  {
    id: '2',
    title: 'Implement Authentication System',
    description: 'Build OAuth2 login flow with JWT refresh tokens and session management for all user roles.',
    priority: 'high',
    dueDate: '2025-05-10',
    assignees: ['Hanna Philips', 'Talan Korsgaard'],
    status: 'todo',
    taskType: 'feature',
    tags: ['auth', 'backend', 'security'],
    createdAt: '2025-09-18T09:00:00.000Z',
    comments: 8,
    links: 3,
    subTasksCompleted: 1,
    subTasksTotal: 5,
  },
  {
    id: '3',
    title: 'Fix Critical Payment Bug',
    description: 'Resolve double-charge issue on subscription renewal triggered by network timeouts.',
    priority: 'high',
    dueDate: '2025-04-15',
    assignees: ['Marcus Webb', 'Davis Donin'],
    status: 'todo',
    taskType: 'bug',
    tags: ['backend', 'blocked', 'payments'],
    createdAt: '2025-10-01T14:22:00.000Z',
    comments: 21,
    links: 2,
    subTasksCompleted: 0,
    subTasksTotal: 2,
  },
  {
    id: '4',
    title: 'Refactor Database Query Layer',
    description: 'Migrate raw SQL queries to ORM to reduce duplication and improve maintainability.',
    priority: 'medium',
    dueDate: '2025-05-20',
    assignees: ['Hanna Philips'],
    status: 'todo',
    taskType: 'testing',
    tags: ['backend', 'refactor'],
    createdAt: '2025-10-05T11:00:00.000Z',
    comments: 4,
    links: 1,
    subTasksCompleted: 2,
    subTasksTotal: 6,
  },
  {
    id: '5',
    title: 'Build Dashboard Analytics Charts',
    description: 'Implement revenue, conversion, and retention charts using a charting library with real-time data.',
    priority: 'medium',
    dueDate: '2026-08-15',
    assignees: ['Sofia Reyes', 'Davis Donin'],
    status: 'in-progress',
    taskType: 'feature',
    tags: ['ux', 'frontend'],
    createdAt: '2025-10-10T08:30:00.000Z',
    comments: 7,
    links: 2,
    subTasksCompleted: 3,
    subTasksTotal: 8,
  },
  {
    id: '6',
    title: 'API Rate Limiting Middleware',
    description: 'Add per-user and per-route rate limiting to prevent abuse and protect service availability.',
    priority: 'high',
    dueDate: '2026-07-10',
    assignees: ['Marcus Webb', 'Hanna Philips'],
    status: 'in-progress',
    taskType: 'bug',
    tags: ['backend', 'security', 'api'],
    createdAt: '2025-10-12T15:45:00.000Z',
    comments: 15,
    links: 4,
    subTasksCompleted: 2,
    subTasksTotal: 4,
  },
  {
    id: '7',
    title: 'User Onboarding Flow Redesign',
    description: 'Streamline the 7-step onboarding to 3 steps based on drop-off analytics. Coordinate with product team.',
    priority: 'medium',
    dueDate: '2025-06-01',
    assignees: ['Sofia Reyes', 'Talan Korsgaard'],
    status: 'in-progress',
    taskType: 'review',
    tags: ['ux', 'frontend', 'blocked'],
    createdAt: '2025-10-08T10:00:00.000Z',
    comments: 19,
    links: 5,
    subTasksCompleted: 1,
    subTasksTotal: 4,
  },
  {
    id: '8',
    title: 'Write API Documentation',
    description: 'Document all public REST endpoints with request/response examples using OpenAPI 3.1 specification.',
    priority: 'low',
    dueDate: '2026-09-30',
    assignees: ['Davis Donin'],
    status: 'in-progress',
    taskType: 'testing',
    tags: ['api', 'docs'],
    createdAt: '2025-10-15T13:00:00.000Z',
    comments: 3,
    links: 1,
    subTasksCompleted: 4,
    subTasksTotal: 10,
  },
  {
    id: '9',
    title: 'Mobile Push Notification Service',
    description: 'Integrate FCM and APNs for cross-platform push notifications with user preference controls.',
    priority: 'low',
    dueDate: '2026-10-20',
    assignees: ['Marcus Webb'],
    status: 'in-progress',
    taskType: 'feature',
    tags: ['backend', 'mobile'],
    createdAt: '2025-10-20T09:15:00.000Z',
    comments: 6,
    links: 2,
    subTasksCompleted: 1,
    subTasksTotal: 5,
  },
  {
    id: '10',
    title: 'Optimize Database Performance',
    description: 'Improve database query efficiency and scalability by adding indices and query plan analysis.',
    priority: 'low',
    dueDate: '2025-04-17',
    assignees: ['Hanna Philips', 'Marcus Webb'],
    status: 'done',
    taskType: 'feature',
    tags: ['backend', 'performance'],
    createdAt: '2025-08-01T10:00:00.000Z',
    comments: 9,
    links: 3,
    subTasksCompleted: 5,
    subTasksTotal: 5,
  },
  {
    id: '11',
    title: 'Improve API Security',
    description: 'Enhance API security measures to protect all endpoints with CORS policy, CSP, and HSTS headers.',
    priority: 'high',
    dueDate: '2025-05-10',
    assignees: ['Marcus Webb'],
    status: 'done',
    taskType: 'feature',
    tags: ['backend', 'security', 'api'],
    createdAt: '2025-08-10T11:30:00.000Z',
    comments: 5,
    links: 1,
    subTasksCompleted: 3,
    subTasksTotal: 3,
  },
  {
    id: '12',
    title: 'Implement API for Task Creation',
    description: 'Develop an API endpoint to create new tasks with validation, auth, and error handling.',
    priority: 'medium',
    dueDate: '2025-09-01',
    assignees: ['Talan Korsgaard', 'Davis Donin'],
    status: 'done',
    taskType: 'feature',
    tags: ['devops', 'automation'],
    createdAt: '2025-07-15T08:00:00.000Z',
    comments: 11,
    links: 2,
    subTasksCompleted: 8,
    subTasksTotal: 8,
  },
];
